const GET_QUIZES_SUCCESS = "GET_QUIZES_SUCCESS";
const GET_QUIZES_ERROR = "GET_QUIZES_ERROR";

const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS";
const FETCH_QUIZ_ERROR = "FETCH_QUIZ_ERROR";

const QUIZ_SET_STATE = "QUIZ_SET_STATE";
const FINISH_QUIZ = "FINISH_QUIZ";
const QUIZ_NEXT_QUESTION = "QUIZ_NEXT_QUESTION";
const QUIZ_RETRY = "QUIZ_RETRY";

const ADD_QUESTION =  "ADD_QUESTION";
const RESET_TEST = "RESET_TEST";

const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_LOGOUT = "AUTH_LOGOUT";

export {
    GET_QUIZES_SUCCESS,
    GET_QUIZES_ERROR,
    FETCH_QUIZ_ERROR,
    FETCH_QUIZ_SUCCESS,
    QUIZ_SET_STATE,
    FINISH_QUIZ,
    QUIZ_NEXT_QUESTION,
    QUIZ_RETRY,
    ADD_QUESTION,
    RESET_TEST,
    AUTH_SUCCESS,
    AUTH_LOGOUT
};